Repository UW-Path/Frontend, pull requests merged in 2020-10, with the labels that each got.

#47 Send post request for excel spreadsheet that returns CSV
  src/components/ExportPage/Export.vue
  src/store/modules/courseSelection.js
  src/views/CourseSelectionPage.vue
Labels: bug

#43 Display SCIENCE, LANG as groups instead of all the courses on the course card
  src/components/Cards/CourseCard.vue
  src/models/courseRequirementModel.js
  src/store/index.js
  src/store/modules/courses.js
Labels: enhancement

#51 Fix deleting added course bug
  src/backendAPI.js
  src/components/Cards/AddCourseCard.vue
  src/components/Modals/RequirementOptionsModal.vue
  src/models/courseRequirementModel.js
Labels: bug

#56 Manage terms
  src/components/CourseSelectionPage/CoursePlan.vue
  src/components/Modals/ProgramSelectionModal.vue
  src/components/Modals/RequirementOptionsModal.vue
  src/store/index.js
  src/store/modules/courseSelection.js
Labels: bug, enhancement

#57 Override only appear in table and resets when being put back in req bar
  src/components/Cards/CourseCard.vue
  src/components/CourseSelectionPage/CoursePlan.vue
  src/components/CourseSelectionPage/RequirementDropdown.vue
  src/components/Modals/RequirementOptionsModal.vue
Labels: bug, enhancement

#58 Multiple Minors
  src/components/Cards/CourseCard.vue
  src/components/Modals/ProgramSelectionModal.vue
  src/components/ProgramChecklistPage/ProgramChecklist.vue
  src/components/ProgramChecklistPage/ProgramChecklistSection.vue
  src/store/index.js
  src/store/modules/courseSelection.js
  src/store/modules/courses.js
  src/views/LandingPage.vue
Labels: enhancement
