Repository UW-Path/Frontend, pull requests merged in 2020-09, with the labels that each got.

#35 Caching
  package-lock.json
  package.json
  src/components/CourseSelectionPage/ProgramSelectionBar.vue
  src/models/ProgramInfoModel.js
  src/models/ProgramModel.js
  src/models/courseInfoModel.js
  src/models/courseModel.js
  src/models/courseRequirementModel.js
  src/store/index.js
  src/store/modules/courseSelection.js
  src/store/modules/courses.js
  src/store/modules/programInfo.js
Labels: bug, dependencies, enhancement

#39 Show warning sign validation
  public/UWPathIcon.ico
  public/index.html
  src/assets/UWPathIcon.png
  src/assets/logo.png
  src/assets/logo.svg
  src/components/Cards/CourseCard.vue
  src/models/courseRequirementModel.js
  src/store/modules/courseSelection.js
Labels: enhancement

#41 Fix excel generating empty table
  src/store/modules/courseSelection.js
Labels: bug

#40 Fix card tags
  src/components/Cards/AddCourseCard.vue
  src/components/Cards/CourseCard.vue
  src/components/CourseSelectionPage/CoursePlan.vue
  src/components/Modals/RequirementOptionsModal.vue
  src/store/modules/courseSelection.js
  src/store/modules/courses.js
Labels: bug

#42 Css figma
  public/index.html
  src/App.vue
  src/assets/cover.png
  src/assets/coverlarge.png
  src/components/Cards/CourseCard.vue
  src/components/CourseSelectionPage/CoursePlan.vue
  src/components/CourseSelectionPage/ProgramSelectionBar.vue
  src/components/CourseSelectionPage/RequirementDropdown.vue
  src/components/Modals/RequirementOptionsModal.vue
  src/components/ProgramChecklistPage/ProgramChecklist.vue
  src/components/ProgramChecklistPage/ProgramChecklistSection.vue
  src/main.js
  src/style.css
  src/views/ContactPage.vue
  src/views/CourseSelectionPage.vue
  src/views/LandingPage.vue
Labels: enhancement

#44 fix modal not displaying right course bug + delete trigger pop up bug
  src/components/Cards/CourseCard.vue
  src/components/CourseSelectionPage/RequirementDropdown.vue
  src/components/Modals/RequirementOptionsModal.vue
Labels: bug

#45 Refresh cache after 24 hours
  src/components/CourseSelectionPage/CoursePlan.vue
  src/components/CourseSelectionPage/RequirementDropdown.vue
  src/components/Modals/ProgramSelectionModal.vue
  src/components/Modals/RequirementOptionsModal.vue
  src/store/index.js
  src/store/modules/courseSelection.js
Labels: enhancement
